// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.1
// source: api/offerpb/offer.proto

package offerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitOfferReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price       int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	PriceDeal   bool     `protobuf:"varint,3,opt,name=price_deal,json=priceDeal,proto3" json:"price_deal,omitempty"`
	ImageUrls   []string `protobuf:"bytes,4,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Isbn        string   `protobuf:"bytes,5,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Publisher   string   `protobuf:"bytes,6,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Edition     int32    `protobuf:"varint,7,opt,name=edition,proto3" json:"edition,omitempty"`
	Description string   `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *SubmitOfferReq) Reset() {
	*x = SubmitOfferReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_offerpb_offer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitOfferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOfferReq) ProtoMessage() {}

func (x *SubmitOfferReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_offerpb_offer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOfferReq.ProtoReflect.Descriptor instead.
func (*SubmitOfferReq) Descriptor() ([]byte, []int) {
	return file_api_offerpb_offer_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitOfferReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitOfferReq) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SubmitOfferReq) GetPriceDeal() bool {
	if x != nil {
		return x.PriceDeal
	}
	return false
}

func (x *SubmitOfferReq) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *SubmitOfferReq) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *SubmitOfferReq) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *SubmitOfferReq) GetEdition() int32 {
	if x != nil {
		return x.Edition
	}
	return 0
}

func (x *SubmitOfferReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type IdVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdVersion) Reset() {
	*x = IdVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_offerpb_offer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdVersion) ProtoMessage() {}

func (x *IdVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_offerpb_offer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdVersion.ProtoReflect.Descriptor instead.
func (*IdVersion) Descriptor() ([]byte, []int) {
	return file_api_offerpb_offer_proto_rawDescGZIP(), []int{1}
}

func (x *IdVersion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_offerpb_offer_proto protoreflect.FileDescriptor

var file_api_offerpb_offer_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x70, 0x62, 0x2f, 0x6f, 0x66,
	0x66, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x70, 0x62, 0x22, 0xe6, 0x01, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x44, 0x65, 0x61, 0x6c, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x73, 0x62, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x62,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1b, 0x0a, 0x09, 0x49,
	0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0x4a, 0x0a, 0x0c, 0x4f, 0x66, 0x66, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x70,
	0x62, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x49, 0x64, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x72, 0x6d, 0x2d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x66,
	0x66, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_offerpb_offer_proto_rawDescOnce sync.Once
	file_api_offerpb_offer_proto_rawDescData = file_api_offerpb_offer_proto_rawDesc
)

func file_api_offerpb_offer_proto_rawDescGZIP() []byte {
	file_api_offerpb_offer_proto_rawDescOnce.Do(func() {
		file_api_offerpb_offer_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_offerpb_offer_proto_rawDescData)
	})
	return file_api_offerpb_offer_proto_rawDescData
}

var file_api_offerpb_offer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_offerpb_offer_proto_goTypes = []interface{}{
	(*SubmitOfferReq)(nil), // 0: offerpb.SubmitOfferReq
	(*IdVersion)(nil),      // 1: offerpb.IdVersion
}
var file_api_offerpb_offer_proto_depIdxs = []int32{
	0, // 0: offerpb.OfferService.SubmitOffer:input_type -> offerpb.SubmitOfferReq
	1, // 1: offerpb.OfferService.SubmitOffer:output_type -> offerpb.IdVersion
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_offerpb_offer_proto_init() }
func file_api_offerpb_offer_proto_init() {
	if File_api_offerpb_offer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_offerpb_offer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitOfferReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_offerpb_offer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_offerpb_offer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_offerpb_offer_proto_goTypes,
		DependencyIndexes: file_api_offerpb_offer_proto_depIdxs,
		MessageInfos:      file_api_offerpb_offer_proto_msgTypes,
	}.Build()
	File_api_offerpb_offer_proto = out.File
	file_api_offerpb_offer_proto_rawDesc = nil
	file_api_offerpb_offer_proto_goTypes = nil
	file_api_offerpb_offer_proto_depIdxs = nil
}
