// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.1
// source: api/reviewpb/review.proto

package reviewpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OfferReview_ReviewStatus int32

const (
	OfferReview_UNKNOWN  OfferReview_ReviewStatus = 0
	OfferReview_APPROVED OfferReview_ReviewStatus = 1
	OfferReview_REJECTED OfferReview_ReviewStatus = 2
)

// Enum value maps for OfferReview_ReviewStatus.
var (
	OfferReview_ReviewStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "APPROVED",
		2: "REJECTED",
	}
	OfferReview_ReviewStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"APPROVED": 1,
		"REJECTED": 2,
	}
)

func (x OfferReview_ReviewStatus) Enum() *OfferReview_ReviewStatus {
	p := new(OfferReview_ReviewStatus)
	*p = x
	return p
}

func (x OfferReview_ReviewStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OfferReview_ReviewStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_reviewpb_review_proto_enumTypes[0].Descriptor()
}

func (OfferReview_ReviewStatus) Type() protoreflect.EnumType {
	return &file_api_reviewpb_review_proto_enumTypes[0]
}

func (x OfferReview_ReviewStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OfferReview_ReviewStatus.Descriptor instead.
func (OfferReview_ReviewStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_reviewpb_review_proto_rawDescGZIP(), []int{2, 0}
}

type Offer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId     int64    `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name        string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price       int64    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	PriceDeal   bool     `protobuf:"varint,5,opt,name=price_deal,json=priceDeal,proto3" json:"price_deal,omitempty"`
	ImageUrls   []string `protobuf:"bytes,6,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Isbn        string   `protobuf:"bytes,7,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Publisher   string   `protobuf:"bytes,8,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Edition     int32    `protobuf:"varint,9,opt,name=edition,proto3" json:"edition,omitempty"`
	Description string   `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Offer) Reset() {
	*x = Offer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reviewpb_review_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_api_reviewpb_review_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_api_reviewpb_review_proto_rawDescGZIP(), []int{0}
}

func (x *Offer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Offer) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Offer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Offer) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Offer) GetPriceDeal() bool {
	if x != nil {
		return x.PriceDeal
	}
	return false
}

func (x *Offer) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Offer) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *Offer) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *Offer) GetEdition() int32 {
	if x != nil {
		return x.Edition
	}
	return 0
}

func (x *Offer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type OfferList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offers []*Offer `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
}

func (x *OfferList) Reset() {
	*x = OfferList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reviewpb_review_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferList) ProtoMessage() {}

func (x *OfferList) ProtoReflect() protoreflect.Message {
	mi := &file_api_reviewpb_review_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferList.ProtoReflect.Descriptor instead.
func (*OfferList) Descriptor() ([]byte, []int) {
	return file_api_reviewpb_review_proto_rawDescGZIP(), []int{1}
}

func (x *OfferList) GetOffers() []*Offer {
	if x != nil {
		return x.Offers
	}
	return nil
}

type OfferReview struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OfferId     int64                    `protobuf:"varint,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Status      OfferReview_ReviewStatus `protobuf:"varint,2,opt,name=status,proto3,enum=reviewpb.OfferReview_ReviewStatus" json:"status,omitempty"`
	Description string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *OfferReview) Reset() {
	*x = OfferReview{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reviewpb_review_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferReview) ProtoMessage() {}

func (x *OfferReview) ProtoReflect() protoreflect.Message {
	mi := &file_api_reviewpb_review_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferReview.ProtoReflect.Descriptor instead.
func (*OfferReview) Descriptor() ([]byte, []int) {
	return file_api_reviewpb_review_proto_rawDescGZIP(), []int{2}
}

func (x *OfferReview) GetOfferId() int64 {
	if x != nil {
		return x.OfferId
	}
	return 0
}

func (x *OfferReview) GetStatus() OfferReview_ReviewStatus {
	if x != nil {
		return x.Status
	}
	return OfferReview_UNKNOWN
}

func (x *OfferReview) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PendingOffersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *PendingOffersReq) Reset() {
	*x = PendingOffersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reviewpb_review_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendingOffersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingOffersReq) ProtoMessage() {}

func (x *PendingOffersReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_reviewpb_review_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingOffersReq.ProtoReflect.Descriptor instead.
func (*PendingOffersReq) Descriptor() ([]byte, []int) {
	return file_api_reviewpb_review_proto_rawDescGZIP(), []int{3}
}

func (x *PendingOffersReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UserOfferReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Count  int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *UserOfferReq) Reset() {
	*x = UserOfferReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_reviewpb_review_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOfferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOfferReq) ProtoMessage() {}

func (x *UserOfferReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_reviewpb_review_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOfferReq.ProtoReflect.Descriptor instead.
func (*UserOfferReq) Descriptor() ([]byte, []int) {
	return file_api_reviewpb_review_proto_rawDescGZIP(), []int{4}
}

func (x *UserOfferReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserOfferReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_reviewpb_review_proto protoreflect.FileDescriptor

var file_api_reviewpb_review_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x70, 0x62, 0x2f, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x70, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x88, 0x02, 0x0a, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x61, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x44, 0x65, 0x61, 0x6c,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69,
	0x73, 0x62, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a,
	0x09, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x70, 0x62, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x73, 0x22, 0xbf, 0x01, 0x0a, 0x0b, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3a,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22,
	0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x70, 0x62, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x0c,
	0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x50, 0x50,
	0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x4a, 0x45, 0x43,
	0x54, 0x45, 0x44, 0x10, 0x02, 0x22, 0x28, 0x0a, 0x10, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x3c, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xd7, 0x01,
	0x0a, 0x0d, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x43, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x73, 0x12, 0x1a, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x70, 0x62, 0x2e, 0x50,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x13, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x70, 0x62, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x15, 0x2e, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x70, 0x62, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3c, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x70, 0x62, 0x2e, 0x4f, 0x66,
	0x66, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x72, 0x6d, 0x2d, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_reviewpb_review_proto_rawDescOnce sync.Once
	file_api_reviewpb_review_proto_rawDescData = file_api_reviewpb_review_proto_rawDesc
)

func file_api_reviewpb_review_proto_rawDescGZIP() []byte {
	file_api_reviewpb_review_proto_rawDescOnce.Do(func() {
		file_api_reviewpb_review_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_reviewpb_review_proto_rawDescData)
	})
	return file_api_reviewpb_review_proto_rawDescData
}

var file_api_reviewpb_review_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_reviewpb_review_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_reviewpb_review_proto_goTypes = []interface{}{
	(OfferReview_ReviewStatus)(0), // 0: reviewpb.OfferReview.ReviewStatus
	(*Offer)(nil),                 // 1: reviewpb.Offer
	(*OfferList)(nil),             // 2: reviewpb.OfferList
	(*OfferReview)(nil),           // 3: reviewpb.OfferReview
	(*PendingOffersReq)(nil),      // 4: reviewpb.PendingOffersReq
	(*UserOfferReq)(nil),          // 5: reviewpb.UserOfferReq
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_api_reviewpb_review_proto_depIdxs = []int32{
	1, // 0: reviewpb.OfferList.offers:type_name -> reviewpb.Offer
	0, // 1: reviewpb.OfferReview.status:type_name -> reviewpb.OfferReview.ReviewStatus
	4, // 2: reviewpb.ReviewService.GetPendingOffers:input_type -> reviewpb.PendingOffersReq
	3, // 3: reviewpb.ReviewService.SubmitReviewResult:input_type -> reviewpb.OfferReview
	5, // 4: reviewpb.ReviewService.GetUserOffers:input_type -> reviewpb.UserOfferReq
	2, // 5: reviewpb.ReviewService.GetPendingOffers:output_type -> reviewpb.OfferList
	6, // 6: reviewpb.ReviewService.SubmitReviewResult:output_type -> google.protobuf.Empty
	2, // 7: reviewpb.ReviewService.GetUserOffers:output_type -> reviewpb.OfferList
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_reviewpb_review_proto_init() }
func file_api_reviewpb_review_proto_init() {
	if File_api_reviewpb_review_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_reviewpb_review_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Offer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reviewpb_review_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reviewpb_review_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferReview); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reviewpb_review_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PendingOffersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_reviewpb_review_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOfferReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_reviewpb_review_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_reviewpb_review_proto_goTypes,
		DependencyIndexes: file_api_reviewpb_review_proto_depIdxs,
		EnumInfos:         file_api_reviewpb_review_proto_enumTypes,
		MessageInfos:      file_api_reviewpb_review_proto_msgTypes,
	}.Build()
	File_api_reviewpb_review_proto = out.File
	file_api_reviewpb_review_proto_rawDesc = nil
	file_api_reviewpb_review_proto_goTypes = nil
	file_api_reviewpb_review_proto_depIdxs = nil
}
