// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: api/reviewpb/review.proto

package reviewpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReviewServiceClient is the client API for ReviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewServiceClient interface {
	GetPendingOffers(ctx context.Context, in *PendingOffersReq, opts ...grpc.CallOption) (*OfferList, error)
	SubmitReviewResult(ctx context.Context, in *OfferReview, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUserOffers(ctx context.Context, in *UserOfferReq, opts ...grpc.CallOption) (*OfferList, error)
}

type reviewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewServiceClient(cc grpc.ClientConnInterface) ReviewServiceClient {
	return &reviewServiceClient{cc}
}

func (c *reviewServiceClient) GetPendingOffers(ctx context.Context, in *PendingOffersReq, opts ...grpc.CallOption) (*OfferList, error) {
	out := new(OfferList)
	err := c.cc.Invoke(ctx, "/reviewpb.ReviewService/GetPendingOffers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewServiceClient) SubmitReviewResult(ctx context.Context, in *OfferReview, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/reviewpb.ReviewService/SubmitReviewResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewServiceClient) GetUserOffers(ctx context.Context, in *UserOfferReq, opts ...grpc.CallOption) (*OfferList, error) {
	out := new(OfferList)
	err := c.cc.Invoke(ctx, "/reviewpb.ReviewService/GetUserOffers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewServiceServer is the server API for ReviewService service.
// All implementations must embed UnimplementedReviewServiceServer
// for forward compatibility
type ReviewServiceServer interface {
	GetPendingOffers(context.Context, *PendingOffersReq) (*OfferList, error)
	SubmitReviewResult(context.Context, *OfferReview) (*emptypb.Empty, error)
	GetUserOffers(context.Context, *UserOfferReq) (*OfferList, error)
	mustEmbedUnimplementedReviewServiceServer()
}

// UnimplementedReviewServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReviewServiceServer struct {
}

func (UnimplementedReviewServiceServer) GetPendingOffers(context.Context, *PendingOffersReq) (*OfferList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingOffers not implemented")
}
func (UnimplementedReviewServiceServer) SubmitReviewResult(context.Context, *OfferReview) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitReviewResult not implemented")
}
func (UnimplementedReviewServiceServer) GetUserOffers(context.Context, *UserOfferReq) (*OfferList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOffers not implemented")
}
func (UnimplementedReviewServiceServer) mustEmbedUnimplementedReviewServiceServer() {}

// UnsafeReviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewServiceServer will
// result in compilation errors.
type UnsafeReviewServiceServer interface {
	mustEmbedUnimplementedReviewServiceServer()
}

func RegisterReviewServiceServer(s grpc.ServiceRegistrar, srv ReviewServiceServer) {
	s.RegisterService(&ReviewService_ServiceDesc, srv)
}

func _ReviewService_GetPendingOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PendingOffersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).GetPendingOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reviewpb.ReviewService/GetPendingOffers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).GetPendingOffers(ctx, req.(*PendingOffersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewService_SubmitReviewResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferReview)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).SubmitReviewResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reviewpb.ReviewService/SubmitReviewResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).SubmitReviewResult(ctx, req.(*OfferReview))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewService_GetUserOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOfferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).GetUserOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reviewpb.ReviewService/GetUserOffers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).GetUserOffers(ctx, req.(*UserOfferReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewService_ServiceDesc is the grpc.ServiceDesc for ReviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reviewpb.ReviewService",
	HandlerType: (*ReviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPendingOffers",
			Handler:    _ReviewService_GetPendingOffers_Handler,
		},
		{
			MethodName: "SubmitReviewResult",
			Handler:    _ReviewService_SubmitReviewResult_Handler,
		},
		{
			MethodName: "GetUserOffers",
			Handler:    _ReviewService_GetUserOffers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/reviewpb/review.proto",
}
