version: '3.8'
services:
  user_service_db:
    container_name: user_service_db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes: 
      - user_volume:/var/lib/postgresql/data
      - ./user-init.sql:/docker-entrypoint-initdb.d/user-init.sql
    networks:
      - user_net

  offer_service_db:
    container_name: offer_service_db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "54321:5432"
    volumes: 
      - offer_volume:/var/lib/postgresql/data
      - ./offer-init.sql:/docker-entrypoint-initdb.d/offer-init.sql
    networks:
      - offer_net


  review_service_db:
    container_name: review_service_db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "54322:5432"
    volumes: 
      - review_volume:/var/lib/postgresql/data
      - ./review-init.sql:/docker-entrypoint-initdb.d/review-init.sql
    networks:
      - review_net

  book_service_db:
    container_name: book_service_db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "54323:5432"
    volumes: 
      - book_volume:/var/lib/postgresql/data
      - ./book-init.sql:/docker-entrypoint-initdb.d/book-init.sql
    networks:
      - book_net

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #      - pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - test_net
  #   restart: unless-stopped


networks:
  offer_net:
    driver: bridge
  review_net:
    driver: bridge
  user_net:
    driver: bridge
  book_net:
    driver: bridge

volumes:
  offer_volume:
  review_volume:
  user_volume:
  book_volume:
  pgadmin: