version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zk1    
    networks:
      - kafka_network
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks:
      - kafka_network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: unless-stopped

networks:
  kafka_network:
    name: kafka_network